/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viws;

import data.Podcast;
import data.PodcastDAO;
import javax.swing.JOptionPane;

/**classe para cadastro de podcasts
 
 */
public class TelaCadastroPodcast extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPodcast
     */
    public TelaCadastroPodcast() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        lblProdutor = new javax.swing.JLabel();
        txtProdutor = new javax.swing.JTextField();
        lblNomeEp = new javax.swing.JLabel();
        txtNomeEp = new javax.swing.JTextField();
        lblNumeroEp = new javax.swing.JLabel();
        ftxtNumeroEp = new javax.swing.JFormattedTextField();
        lblDuracao = new javax.swing.JLabel();
        ftxtDuracao = new javax.swing.JFormattedTextField();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        blnListagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Cenaflix");

        lblCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCadastrar.setText("Cadastrar Podcast");

        lblProdutor.setText("Produtor");

        lblNomeEp.setText("Nome do Episódio");

        lblNumeroEp.setText("Nº do Episódio");

        ftxtNumeroEp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lblDuracao.setText("Duração");

        ftxtDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        lblUrl.setText("URL do repositório");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        blnListagem.setText("Ver Listagem");
        blnListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blnListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProdutor)
                            .addComponent(txtProdutor)
                            .addComponent(lblNomeEp)
                            .addComponent(txtNomeEp)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNumeroEp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtNumeroEp, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addComponent(lblDuracao)
                            .addComponent(ftxtDuracao)
                            .addComponent(lblUrl)
                            .addComponent(txtUrl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblCadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(blnListagem)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadastrar)
                .addGap(18, 18, 18)
                .addComponent(lblProdutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeEp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroEp)
                    .addComponent(ftxtNumeroEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDuracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUrl)
                .addGap(18, 18, 18)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blnListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
/**botão para voltar para tela de listagem
 * 
 * @param evt 
 */
    private void blnListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blnListagemActionPerformed
      
        this.dispose();
        
    }//GEN-LAST:event_blnListagemActionPerformed

    
    
    /**botão para catdastrar novo podcast
     * 
     * @param evt 
     */
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       
        if(!validaCampos()) {
            
            Podcast podcast = new Podcast();
            
            podcast.setProdutor(txtProdutor.getText());
            podcast.setNome_episodio(txtNomeEp.getText());
            podcast.setNumero_episodio(Integer.parseInt(ftxtNumeroEp.getText()));
            podcast.setDuracao(ftxtDuracao.getText());
            podcast.setUrl_repositorio(txtUrl.getText());
            
            PodcastDAO podcastDAO = new PodcastDAO();
            
            podcastDAO.cadastrar(podcast);
            
            
            txtProdutor.setText("");
            txtNomeEp.setText("");
            ftxtNumeroEp.setText("");
            ftxtDuracao.setText("");
            txtUrl.setText("");
            
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPodcast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blnListagem;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JFormattedTextField ftxtDuracao;
    private javax.swing.JFormattedTextField ftxtNumeroEp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblNomeEp;
    private javax.swing.JLabel lblNumeroEp;
    private javax.swing.JLabel lblProdutor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JTextField txtNomeEp;
    private javax.swing.JTextField txtProdutor;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables



/**valida todos os campos
 * 
 * @return 
 */
    private boolean validaCampos(){
        
        
     String produtor = txtProdutor.getText();
     String numeroEp = ftxtNumeroEp.getText();
     String duracao = ftxtDuracao.getText();
     
     boolean valido = true; 

//     valida se os campos estão preenchidos
     if(txtProdutor.getText().trim().isEmpty() || txtNomeEp.getText().trim().isEmpty() || ftxtNumeroEp.getText().trim().isEmpty() 
             || ftxtDuracao.getText().trim().isEmpty() || txtUrl.getText().trim().isEmpty()){
        
         JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preenchidos. ");
         
     } else{
         
         boolean strProdutor = produtor.matches("[a-zA-Z]{1,150}");
         boolean strNumero = numeroEp.matches("[0-9]{1,3}");
         boolean strDuracao = duracao.matches("[0-9]{2}[:][0-9]{2}");
         
        //     valida se os campos estão preenchidos corretamente 
        if(strProdutor == false && strNumero == false && strDuracao == false){
         
            JOptionPane.showMessageDialog(rootPane, """
                                                    O campo Produtor  deve conter apenas letras.
                                                    O campo Nº do episódio deve conter apenas. 
                                                    O campo Duração deve ser no formato (00:00).""");
          
        } else if(strProdutor == false){
         
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! O campo Produtor  deve conter apenas letras.");
          
        } else if(strNumero == false){
         
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! O campo Nº do episódio deve conter apenas. ");
         
        } else if(strDuracao == false){
         
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! O campo Duração deve ser no formato (00:00). ");
         
        } else{
         
         valido = false; // se naõ estiver preenchido retorna false
        }
     }
     
     return valido;  //  se estiver preenchido retorna true
     
    }
    
    
  }





